### ISSUE TITLE
Summary/description for visualisations

### ISSUE THREAD

**Issue by long39ng** [CorrelAid/correlaidx-challenge-bremen#5]
Two short passages, one for NUTS-1 and one for NUTS-3

**Comment by christine-hvw** [comment]
For NUTS-3:
Visualization on the NUTS-3 level nicely shows how commuting centers around the larger cities in each region. Looking at total inflow for 2019, the top five cities are Munich, Franfurt a.M., Hamburg, Berlin and Cologne. They are also among those with the highest total outflow. When scaling data in relation to population size, we can also observe the important role of mid-sized cites for surrounding regions. This pattern becomes especially prominent when looking at maps for balance statistics (e.g. in Bavaria and Baden-Wuerttemberg).
